// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHL2YNOnJPYnOJ4oBPAi2H1hQgtDLSlQ',
    appId: '1:680114113653:web:3bd1c302bbd052ba7c3c3c',
    messagingSenderId: '680114113653',
    projectId: 'raktsetu-dev-123',
    authDomain: 'raktsetu-dev-123.firebaseapp.com',
    storageBucket: 'raktsetu-dev-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSwAGSiKp7rtuxzQe7GcTvJcQx13tiBo',
    appId: '1:680114113653:android:3385305c766193087c3c3c',
    messagingSenderId: '680114113653',
    projectId: 'raktsetu-dev-123',
    storageBucket: 'raktsetu-dev-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qCFVX0jvD6kOapo8l0h3IFzoZbH_JR0',
    appId: '1:680114113653:ios:d8fe5aa0549dc56f7c3c3c',
    messagingSenderId: '680114113653',
    projectId: 'raktsetu-dev-123',
    storageBucket: 'raktsetu-dev-123.firebasestorage.app',
    iosClientId: '680114113653-6r8co0qruvnc77onrqnbrter7cpo41mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.raktsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qCFVX0jvD6kOapo8l0h3IFzoZbH_JR0',
    appId: '1:680114113653:ios:9b0ce7ef969f82a37c3c3c',
    messagingSenderId: '680114113653',
    projectId: 'raktsetu-dev-123',
    storageBucket: 'raktsetu-dev-123.firebasestorage.app',
    iosClientId: '680114113653-6bn9j15hca0orp9kjdhi370ipliiokoq.apps.googleusercontent.com',
    iosBundleId: '111',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuHL2YNOnJPYnOJ4oBPAi2H1hQgtDLSlQ',
    appId: '1:680114113653:web:81a926443ee3d7bf7c3c3c',
    messagingSenderId: '680114113653',
    projectId: 'raktsetu-dev-123',
    authDomain: 'raktsetu-dev-123.firebaseapp.com',
    storageBucket: 'raktsetu-dev-123.firebasestorage.app',
  );
}
