// ===========================
// RaktSetu — Firebase Options (Placeholder)
// ===========================
//
// This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure
//
// DO NOT manually edit this file. It will be overwritten
// when you run `flutterfire configure` again.
//
// To regenerate:
//   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   2. Run: flutterfire configure --project=raktsetu-prod
//   3. This file will be auto-populated with your Firebase config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for each platform.
/// Generated by FlutterFire CLI — replace placeholder values after running
/// `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported.');
      default:
        throw UnsupportedError('Unknown platform.');
    }
  }

  // ── Placeholder values — replaced by `flutterfire configure` ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'raktsetu-prod',
    authDomain: 'raktsetu-prod.firebaseapp.com',
    storageBucket: 'raktsetu-prod.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'raktsetu-prod',
    storageBucket: 'raktsetu-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'raktsetu-prod',
    storageBucket: 'raktsetu-prod.appspot.com',
    iosBundleId: 'com.raktsetu.app',
  );
}
